from datetime import datetime, timedelta
from models import Product


# Kezdő időpont (20 nappal ezelőtt)
base_date = datetime.now() - timedelta(days=20)

# 20 termék létrehozása
products: list[Product] = [
    Product(
        id=1,
        name="Piros póló",
        stock=15,
        color="red",
        price=2999.99,
        created_at=base_date,
        updated_at=None,
    ),
    Product(
        id=2,
        name="Zöld nadrág",
        stock=8,
        color="green",
        price=4500.50,
        created_at=base_date + timedelta(days=1),
        updated_at=None,
    ),
    Product(
        id=3,
        name="Kék sapka",
        stock=0,
        color="blue",
        price=1500.00,
        created_at=base_date + timedelta(days=2),
        updated_at=None,
    ),
    Product(
        id=4,
        name="Sárga cipő",
        stock=12,
        color="yellow",
        price=8999.99,
        created_at=base_date + timedelta(days=3),
        updated_at=None,
    ),
    Product(
        id=5,
        name="Piros kabát",
        stock=5,
        color="red",
        price=15999.00,
        created_at=base_date + timedelta(days=4),
        updated_at=None,
    ),
    Product(
        id=6,
        name="Zöld pulóver",
        stock=20,
        color="green",
        price=3500.00,
        created_at=base_date + timedelta(days=5),
        updated_at=None,
    ),
    Product(
        id=7,
        name="Kék farmer",
        stock=10,
        color="blue",
        price=5999.99,
        created_at=base_date + timedelta(days=6),
        updated_at=None,
    ),
    Product(
        id=8,
        name="Sárga sál",
        stock=25,
        color="yellow",
        price=999.50,
        created_at=base_date + timedelta(days=7),
        updated_at=None,
    ),
    Product(
        id=9,
        name="Piros zokni",
        stock=50,
        color="red",
        price=500.00,
        created_at=base_date + timedelta(days=8),
        updated_at=None,
    ),
    Product(
        id=10,
        name="Zöld táska",
        stock=3,
        color="green",
        price=7500.00,
        created_at=base_date + timedelta(days=9),
        updated_at=None,
    ),
    Product(
        id=11,
        name="Kék kesztyű",
        stock=0,
        color="blue",
        price=1200.00,
        created_at=base_date + timedelta(days=10),
        updated_at=None,
    ),
    Product(
        id=12,
        name="Sárga esernyő",
        stock=7,
        color="yellow",
        price=2500.00,
        created_at=base_date + timedelta(days=11),
        updated_at=None,
    ),
    Product(
        id=13,
        name="Piros öv",
        stock=18,
        color="red",
        price=1800.00,
        created_at=base_date + timedelta(days=12),
        updated_at=None,
    ),
    Product(
        id=14,
        name="Zöld csizma",
        stock=6,
        color="green",
        price=12000.00,
        created_at=base_date + timedelta(days=13),
        updated_at=None,
    ),
    Product(
        id=15,
        name="Kék ing",
        stock=14,
        color="blue",
        price=3999.00,
        created_at=base_date + timedelta(days=14),
        updated_at=None,
    ),
    Product(
        id=16,
        name="Sárga short",
        stock=9,
        color="yellow",
        price=2800.00,
        created_at=base_date + timedelta(days=15),
        updated_at=None,
    ),
    Product(
        id=17,
        name="Piros karkötő",
        stock=30,
        color="red",
        price=800.00,
        created_at=base_date + timedelta(days=16),
        updated_at=None,
    ),
    Product(
        id=18,
        name="Zöld kendő",
        stock=11,
        color="green",
        price=1500.00,
        created_at=base_date + timedelta(days=17),
        updated_at=None,
    ),
    Product(
        id=19,
        name="Kék hátizsák",
        stock=4,
        color="blue",
        price=9500.00,
        created_at=base_date + timedelta(days=18),
        updated_at=None,
    ),
    Product(
        id=20,
        name="Sárga kalap",
        stock=13,
        color="yellow",
        price=3200.00,
        created_at=base_date + timedelta(days=19),
        updated_at=None,
    ),
]


# Helper függvény új ID generálásához
def get_next_id() -> int:
    return 1 if not products else max(product.id for product in products) + 1
